#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Compiling solvers 

cd surfaceFlowBoundaryConditions/
wmake libso criticalDepthOverlandOutletBC
wmake libso freeFlowOutletBC
wmake libso imperviousSurfaceFlowBC
wmake libso specifiedConstantOverlandDischargeBC
cd ..
wmake surfaceFlowFOAM

